version: "3"
services:
  web:
    image: ${PROJECT_IMAGE_NAME:-login}
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 8080:8080
    volumes:
      - ./logs:/var/log/login
    depends_on:
      - db
  db:
    image: postgres:13
    restart: unless-stopped
    environment:
      POSTGRES_DB: login
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_INITDB_ARGS: --encoding=UTF-8
      LC_COLLATE: "C"
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  postgres-data:
